# development:
#   adapter: mongodb
#   database: ferret_development
#   host: localhost
#   port: nil
# 
# test:
#   adapter: mongodb
#   database: ferret_test
#   host: localhost
#   port: nil
# 
# production:
#   adapter: mongodb
#   database: ferret_production
#   host: localhost
#   port: nil
  # hosts:
  # - - localhost
  #   - nil
  # - - staff.mongohq.com
  #   - 10015

mongo_test: &mongo_test
  adapter: mongodb
  database: ferret_test
  host: localhost
  port: ~  

mongo_adapter_test:
  <<: *mongo_test
  
ferret_gem_test:
  <<: *mongo_test